apiVersion: v1
kind: Service
metadata:
  name: petclinic-g
spec:
  ports:
    - protocol: "TCP"
      port: 80   # Port inside the cluster
      targetPort: 8080 # Port exposed to the outside
  selector:
    app: petclinic-g
  type: NodePort