apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-g
spec:
  selector:
    matchLabels:
      app: petclinic-g
  replicas: 4
  template:
    metadata:
      labels:
        app: petclinic-g
    spec:   
      containers:
        - name: petclinic-g
          image: 818104450483.dkr.ecr.us-east-1.amazonaws.com//pc-ecr:replaceImagetag
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_URL
              valueFrom :
                configMapKeyRef :
                  name : configmap-petclinic
                  key : MYSQL_URL