apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-g
spec:
  selector:
    matchLabels:
      app: petclinic-g
  replicas: 2
  template:
    metadata:
      labels:
        app: petclinic-g
    spec:
      containers:
        - name: petclinic-g
          image: shivanishivani/clinic09:12
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_URL
              valueFrom :
                configMapKeyRef :
                  name : configmap-petclinic
                  key : MYSQL_URL